### ISSUE TITLE
Report unused images/videos

### ISSUE THREAD

**Issue by danverde** [byuitechops/d2l-to-canvas-conversion-tool#106]
Identify which images/videos are used in the course in quizzes, etc.

**Comment by zlw11063** [comment]
We'll need to upgrade the current files-find-used-content module to also locate images and videos that aren't used in the course. We may want to update this one to be post-import. We'll discuss it and see what the best options are.

**Comment by maeashley** [comment]
My latest commit fixes this. All images, video and audio files, as well as documents are accounted for under [this fix](https://github.com/byuitechops/files-find-used-content/commit/7efd063479404f60a0870ff2920f96f5f133fa3c)
