### ISSUE TITLE
Course Settings (course-settings)

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#110]
Talk to Zach or Ashley about these settings if you can't find them. Most are located in the course "settings" tab. The child module needs to set the following settings on the Canvas course:

Enable the "New Gradebook" Feature Option

Set the "Term" to "Master"

Set the language to "US English"

Set the License to "Private"

Set the course visibility to "Course"

Set the Syllabus Visibility to "Institution"

Set the "Format" to "Online"

Set the Grading Scheme to "BYUI" (this one might be more complicated since it is a custom grading scheme)

Set the SIS ID (Corey knows how to get this)

"Disable Comments" under "More Options" should be *unchecked*

**Comment by danverde** [comment]
Duplicate
