### ISSUE TITLE
Remove Blank Page Headers

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#114]
When D2L has a description on a module, Canvas creates a blank page header in its place. Canvas does not have descriptions on modules. 

We need to remove that blank page header. If the description is less than five words, and the module title is a generic title (i.e. "Week 05") then we need to put the description onto the module title ("Week 05" becomes "Week 05: Processing Meatloaf").

**Comment by sethchilders92** [comment]
Ready for review

**Comment by danverde** [comment]
Reviewed
