### ISSUE TITLE
Enforce platform setting

### ISSUE THREAD

**Issue by danverde** [byuitechops/d2l-to-canvas-conversion-tool#119]
Each child module that is required for at least one platform must check the current platform before running. This way required child modules can remain in the agenda no matter which type of course is running. use the following code to do so:
```js
var validPlatforms = ['online', 'pathway'];
    if (validPlatforms.includes(course.settings.platform)) {
        course.message('Invalid platform. Skipping child module');
        stepCallback(null, course);
        return;
    }
```

**Comment by danverde** [comment]
The following child modules need to check the setting:

Navigation Tabs,
Publish Settings
Reorganize File Structure
Web Feature Update
Make course a blueprint course
Blueprint Lock Items
Create Homepage
Delete [CO~#] Assignments
Instructor Resources Setup
Set Syllabus
Disperse Welcome Folder
Notes from Instructor DBs

**Comment by zlw11063** [comment]
@danverde I've seen a lot of the child modules now do this. Is this finished?

**Comment by danverde** [comment]
Yes it is
