### ISSUE TITLE
Crashes program if needed dirs don't exist

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#35]
These four directories are needed by the program:

D2LOriginal
D2LProcessing
D2LProcessed
D2LReady

We need to set the program to create them if they don't exist.

**Comment by danverde** [comment]
The current version (commit 5669c92fa3e) Doesn't use D2LOriginal at all

**Comment by zlw11063** [comment]
When we integrate the downloader, it will.

**Comment by zlw11063** [comment]
This is fixed....I think? 

Used mkdirp directory to build missing directories.

**Comment by zlw11063** [comment]
Scratch my above comment. We just included the empty folders as part of the Git repository, so this won't be an issue unless on an older version or someone goes all slice 'n dice on their download.
