### ISSUE TITLE
How do we upload converter and downloader as node packages?

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#39]
Do we have an account to do it under? Uploading both as individual tools will make it easier to work on them separately, etc.

**Comment by zlw11063** [comment]
Learned from Josh you can install node modules using the git url instead of referencing an npm official package.

**Comment by danverde** [comment]
Just for the sake of information, you use `npm publish` to make a package live (and `npm unpublish` to take it down)
