### ISSUE TITLE
Chalk makes report.json difficult to read

### ISSUE THREAD

**Issue by danverde** [byuitechops/d2l-to-canvas-conversion-tool#43]
Is it worth changing?

**Comment by zlw11063** [comment]
I was mostly just messing around with chalk. I think we were planning on making the report useful, at some point. Chalk would be useful for pointing out errors, but otherwise, we can remove it.

**Comment by zlw11063** [comment]
Removed chalk from what was being saved to the report object, causing odd issues with saving/opening the JSON report.
