### ISSUE TITLE
Run the verifier on a fatal error?

### ISSUE THREAD

**Issue by danverde** [byuitechops/d2l-to-canvas-conversion-tool#45]
If a fatal error is thrown, the verifier doesn't run, which allows us to pass null or undefined to main which crashes the whole thing (:

**Comment by zlw11063** [comment]
If a fatal error is thrown, aren't we crashing the whole thing anyway? *much ponder* Can you show me this when I get back into the office?

**Comment by danverde** [comment]
But we still want to catch the fatal error and handle it nicely. This one is uncaught.

**Comment by zlw11063** [comment]
Fatal errors only happen at the top level, so we will handle it just via console.log or another method from there. That's the conclusion Daniel and I came to discussing it at work.
