### ISSUE TITLE
Publish State

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#56]
Set the publish state for common modules (i.e. the instructor resources need to be unpublished). Sets the visibility access level for different modules within the modules page.

**Comment by zlw11063** [comment]
@YuraVasiuk, can we go over this when we're in the office together? It looked ready to go last we looked at it, so we can probably make sure testing is good to go and then put it into the main tool.

**Comment by YuraVasiuk** [comment]
Sure Zach.  I will be at work in about 20 minutes.

Yura Vasiuk
