### ISSUE TITLE
Menu Option Visibility

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/d2l-to-canvas-conversion-tool#59]
We'll need to turn off/on the visibility for different items in the menu for canvas. I.e. students won't need to see the Pages or Discussions.

**Comment by zlw11063** [comment]
Yura has been working on this, and it is nearing completion. It needs review and a little more testing, then we will try implementing it into the main tool.

**Comment by danverde** [comment]
Repo is located here: https://github.com/byuitechops/set-navigation-tabs
